language: rust
before_script:
- rustup component add rustfmt-preview
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
- cargo fmt --all -- --write-mode=diff
- cargo build
- cargo test
